# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'bidcal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Firebase
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
  
  # Google Sign-In
  pod 'GoogleSignIn'
  
  # Google Mobile Ads
  pod 'Google-Mobile-Ads-SDK'

  target 'bidcalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bidcalUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
